### PR TITLE
fix: Make props optional in `rerender` function returned from `renderHookToSnapshotStream`

### LINKED ISSUE #13: `rerender` function returned from `renderHookToSnapshotStream` requires a props argument even when its optional
Take the following test:

```ts
const { takeSnapshot, getCurrentSnapshot, rerender } =
  await renderHookToSnapshotStream(
    () => {
      return useLazyQuery(query, {
        fetchPolicy: "cache-first",
        variables: { id: "1" },
      });
    },
    {
      wrapper: ({ children }) => (
        <ApolloProvider client={client}>{children}</ApolloProvider>
      ),
    }
  );
```

When I try to use `rerender`, I get an error that an argument is required:

```ts
await rerender();
// ^ Expected 1 arguments, but got 0.
```

Ideally the argument is only required if the hook callback requires props.

### PR DESCRIPTION
**Pull request by jerelmiller**
Fixes #13 

Makes the `props` argument optional in the `rerender` function returned from `renderHookToSnapshotStream`. This aligns it with RTL's [`rerender` function](https://github.com/testing-library/react-testing-library/blob/85ac2534a59abd38880011e77da4bb8c716eba84/types/index.d.ts#L159) returned from `renderHook`.

### CODE REVIEW

File: src/renderHookToSnapshotStream.tsx [hunk 1]
```diff
@@ -41,11 +41,21 @@ export interface SnapshotStream<Snapshot, Props> extends Assertable {
...
+ * if `Arg` can be `undefined`, replace it with `void` to make type represent an optional argument in a function argument position
+ */
+type VoidOptionalArg<Arg> = Arg extends any // distribute members of a potential `Props` union
+  ? undefined extends Arg
+    ? // eslint-disable-next-line @typescript-eslint/no-invalid-void-type
+      void
+    : Arg
+  : Arg
+
+export async function renderHookToSnapshotStream<ReturnValue, Props = void>(
```
Comment (phryneas) [inline src/renderHookToSnapshotStream.tsx:58]: We can actually reach the same result, but more situational and "correct" by defaulting `Props` to `void` instead of the default `unknown`.

This way if you have an actual argument defined for the function, it will stay required, but if there is no argument it will be `void`, making it optional.

We do need a little bit more work to also correctly work if the function argument is optional from the start - the `VoidOptionalArg` takes care of that.

**Comment by jerelmiller** [comment]
@phryneas I would agree, I like the idea of making it optional only if its truly optional. RTL ended up changing my mind, but happy to go this route for this package. Thanks for the assist!
